//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnappo.Portfolio.Application.Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConversationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConversationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gnappo.Portfolio.Application.Bot.Resources.ConversationResources", typeof(ConversationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eventualmente come posso contattarti?.
        /// </summary>
        public static string AskContact {
            get {
                return ResourceManager.GetString("AskContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to come mai ti trovi qui?.
        /// </summary>
        public static string AskReason {
            get {
                return ResourceManager.GetString("AskReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorrei cambiare argomento.
        /// </summary>
        public static string ChangeTopic {
            get {
                return ResourceManager.GetString("ChangeTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scusami ma non ho capito cosa intendi....
        /// </summary>
        public static string DontUnderstand {
            get {
                return ResourceManager.GetString("DontUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bhe, in questo caso allora....
        /// </summary>
        public static string Farewell {
            get {
                return ResourceManager.GetString("Farewell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ora che abbiamo rotto il ghiaccio, posso sapere il tuo nome?.
        /// </summary>
        public static string FriendlyAskName {
            get {
                return ResourceManager.GetString("FriendlyAskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao, mi chiamo Mattia. Cosa ti porta qui?.
        /// </summary>
        public static string GreetingAndAskIntent {
            get {
                return ResourceManager.GetString("GreetingAndAskIntent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorrei contattarti.
        /// </summary>
        public static string IntentContactYou {
            get {
                return ResourceManager.GetString("IntentContactYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me lo stavo giusto chiedendo.
        /// </summary>
        public static string IntentGoAway {
            get {
                return ResourceManager.GetString("IntentGoAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come contattarmi.
        /// </summary>
        public static string IntentHowContactYou {
            get {
                return ResourceManager.GetString("IntentHowContactYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorrei sapere qualcosa di te.
        /// </summary>
        public static string IntentKowYou {
            get {
                return ResourceManager.GetString("IntentKowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saltiamo i convenevoli.
        /// </summary>
        public static string IntentSkipPleasantries {
            get {
                return ResourceManager.GetString("IntentSkipPleasantries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrivimi un messaggio.
        /// </summary>
        public static string MailMe {
            get {
                return ResourceManager.GetString("MailMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to piacere di conoscerti {0}.
        /// </summary>
        public static string NiceToMeetYou {
            get {
                return ResourceManager.GetString("NiceToMeetYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferisco non dirlo.
        /// </summary>
        public static string NoComment {
            get {
                return ResourceManager.GetString("NoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contattami su Linkedin.
        /// </summary>
        public static string ReachMeOnLinkedin {
            get {
                return ResourceManager.GetString("ReachMeOnLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorrei vedere altri post.
        /// </summary>
        public static string ShowAllPosts {
            get {
                return ResourceManager.GetString("ShowAllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vuoi sapere altro? posso suggerirti qualcosa. se preferisci puoi provare a farmi una domanda.
        /// </summary>
        public static string SuggestOtherTopics {
            get {
                return ResourceManager.GetString("SuggestOtherTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puoi provare a farmi una domanda, oppure posso provare a suggerirti qualcosa..
        /// </summary>
        public static string SuggestStuff {
            get {
                return ResourceManager.GetString("SuggestStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se ti interessa posso darti qualche dettaglio.
        /// </summary>
        public static string SuggestTopics {
            get {
                return ResourceManager.GetString("SuggestTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to questo sono io.
        /// </summary>
        public static string ThisIsMe {
            get {
                return ResourceManager.GetString("ThisIsMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sto facendo recuiting.
        /// </summary>
        public static string UserReason1 {
            get {
                return ResourceManager.GetString("UserReason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curiosità professionale.
        /// </summary>
        public static string UserReason2 {
            get {
                return ResourceManager.GetString("UserReason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho cliccato un link a caso.
        /// </summary>
        public static string UserReason3 {
            get {
                return ResourceManager.GetString("UserReason3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purtroppo le mie risposte sono limitate, dovrai farmi le domande giuste.
        /// </summary>
        public static string WeakAI {
            get {
                return ResourceManager.GetString("WeakAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao {0}, ben tornato. cosa ti riporta qui?.
        /// </summary>
        public static string WelcomeBackAndAskIntent {
            get {
                return ResourceManager.GetString("WelcomeBackAndAskIntent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lavoro nel settore salute da più di 10 anni e mi occupo di UX design e di software development.
        /// </summary>
        public static string WhatIDo {
            get {
                return ResourceManager.GetString("WhatIDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi piacciono i videogiochi, la pizza e creare cose utili e facili da usare.
        /// </summary>
        public static string WhatILike {
            get {
                return ResourceManager.GetString("WhatILike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con chi ho il piacere di parlare?.
        /// </summary>
        public static string WhoAreYou {
            get {
                return ResourceManager.GetString("WhoAreYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi chiamo Pietro Mattia Guglielmo, i nomi sono intercambiabili ma io preferisco Mattia.
        /// </summary>
        public static string WhoIAm {
            get {
                return ResourceManager.GetString("WhoIAm", resourceCulture);
            }
        }
    }
}
